module.exports = {
	"prefix": process.env?.PREFIX ?? "!",
	"guildID": process.env.GUILD_ID,
	"clientID": process.env.CLIENT_ID,
	"botToken": process.env.BOT_TOKEN,
	"redTick": process.env?.RED_TICK ?? "",
	"greenTick": process.env?.GREEN_TICK ?? "",
	"CustomEmoji": process.env?.CUSTOM_EMOJI ?? "",
	"red": process.env?.RED ?? "#F14948",
	"green": process.env?.GREEN ?? "#45B681",
	"lightBlue": process.env?.LIGHT_BLUE ?? "#00D2FF",
	"darkGreen": process.env?.DARK_GREEN ?? "#008369",
    "robloxclientID": process.env.ROBLOX_CLIENT_ID,
    "robloxtoken": process.env.ROBLOX_TOKEN,
    "MongooseURI": process.env.MONGO_URI,
    "port": process.env?.PORT ?? 80,
	"verificationChannel": process.env.VERIFICATION_CHANNEL,
	"baseUrl": process.env.BASE_URI,
}
